MOC=moc
MOC_FILES=moc_mainwindow.cpp moc_loggingwidget.cpp moc_glview.cpp moc_scenetreewidget.cpp moc_scenemodel.cpp


moc: $(MOC_FILES)

moc_mainwindow.cpp: mainwindow.h
	$(MOC) $? -o $@

moc_loggingwidget.cpp: loggingwidget.h
	$(MOC) $? -o $@

moc_glview.cpp: glview.h
	$(MOC) $? -o $@

moc_scenetreewidget.cpp: scenetreewidget.h
	$(MOC) $? -o $@

moc_scenemodel.cpp: scenemodel.h
	$(MOC) $? -o $@


clean:
	rm -rf $(MOC_FILES)
